-- 2019/5/1
-- database: bbs

DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `user_info`;
DROP TABLE IF EXISTS `open_user`;
DROP TABLE IF EXISTS `loginlog`;
DROP TABLE IF EXISTS `grade`;
DROP TABLE IF EXISTS `role`;
DROP TABLE IF EXISTS `role_user`;
DROP TABLE IF EXISTS `follow`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `article`;
DROP TABLE IF EXISTS `favorite`;
DROP TABLE IF EXISTS `browse`;
DROP TABLE IF EXISTS `upvote`;
DROP TABLE IF EXISTS `comment`;
DROP TABLE IF EXISTS `guestbook`;

SET @saved_cs_client = @@character_set_client;
SET character_set_client = utf8;

-- 创建用户信息
CREATE TABLE IF NOT EXISTS user(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL COMMENT '登录名',
	password VARCHAR(100) NOT NULL,
	email VARCHAR(255) DEFAULT '0',
	phone VARCHAR(13) DEFAULT '0',
	profile VARCHAR(255) NOT NULL,
	-- grade INT UNSIGNED NOT NULL COMMENT '用户等级',
	is_active VARCHAR(1) DEFAULT '1' COMMENT '默认激活',
	is_admin VARCHAR(1) DEFAULT '0' COMMENT '默认普通用户'
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 用户信息
CREATE TABLE IF NOT EXISTS user_info(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	gender ENUM('male', 'female', 'secret') DEFAULT 'secret',
	following INT UNSIGNED DEFAULT 0 COMMENT '关注数量',
	follower INT UNSIGNED DEFAULT 0 COMMENT '粉丝数量',
	hobbies VARCHAR(100) DEFAULT '没有留下',
	article INT UNSIGNED DEFAULT 0 COMMENT '文章数量',
	description VARCHAR(200) DEFAULT '没有留下' COMMENT '个人介绍',
	FOREIGN KEY(user_id) REFERENCES user(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 第三方登录
CREATE TABLE IF NOT EXISTS open_user(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	open_id VARCHAR(100) NOT NULL,
	access_token VARCHAR(100) NOT NULL,
	nick_name VARCHAR(100) NOT NULL,
	avatar VARCHAR(500) NOT NULL,
	open_type VARCHAR(1) DEFAULT '0' COMMENT '第三方类型,0-qq,1-weixin,2-weibo',
	FOREIGN KEY(user_id) REFERENCES user(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 登录日志
CREATE TABLE IF NOT EXISTS loginlog(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	ip VARCHAR(16) DEFAULT '0' COMMENT '登录ip，默认无ip记录',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	FOREIGN KEY(user_id) REFERENCES user(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 等级
CREATE TABLE IF NOT EXISTS grade(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	browse INT UNSIGNED DEFAULT 0 ,
	upvote INT UNSIGNED DEFAULT 0 ,
	signin INT UNSIGNED DEFAULT 0 COMMENT '登录签到',
	comment INT UNSIGNED DEFAULT 0 COMMENT '评论',
	FOREIGN KEY(user_id) REFERENCES user(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 角色管理
CREATE TABLE IF NOT EXISTS role(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	role_name VARCHAR(100) NOT NULL,
	role_val INT NOT NULL
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 用户角色
CREATE TABLE IF NOT EXISTS role_user(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL,  
	role_id INT UNSIGNED NOT NULL, 
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(role_id) REFERENCES role(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 关注
CREATE TABLE IF NOT EXISTS follow(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL,  
	follower_id INT UNSIGNED NOT NULL COMMENT '粉丝id', 
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(follower_id) REFERENCES role(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 帖子分类
CREATE TABLE IF NOT EXISTS category(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	pid INT DEFAULT -1 COMMENT '父分类,默认无父分类',
	category_name VARCHAR(100) NOT NULL,
	description VARCHAR(255) NOT NULL,
	paper_count INT UNSIGNED DEFAULT 0,
	browse INT UNSIGNED DEFAULT 0,
	status VARCHAR(1) DEFAULT '1',
	sorts INT UNSIGNED DEFAULT 0
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 文章
CREATE TABLE IF NOT EXISTS article(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL, 
	category_id INT UNSIGNED NOT NULL, 
	title VARCHAR(255) NOT NULL,
	pic VARCHAR(255) DEFAULT '0' COMMENT '默认无标题图片',
	description VARCHAR(512) DEFAULT '没有描述' COMMENT '短描述',
	top VARCHAR(1) DEFAULT '0' COMMENT '默认非置顶文章',
	content TEXT NOT NULL,
	status VARCHAR(1) DEFAULT '1',
	upvote INT UNSIGNED DEFAULT 0,
	downvote INT UNSIGNED DEFAULT 0,
	comment_count INT UNSIGNED DEFAULT 0,
	browse INT UNSIGNED DEFAULT 0,
	favorite INT UNSIGNED DEFAULT 0 COMMENT '收藏数',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(category_id) REFERENCES category(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 文章收藏
CREATE TABLE IF NOT EXISTS favorite(
	id INT  PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL, 
	article_id INT UNSIGNED NOT NULL, 
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(article_id) REFERENCES article(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 文章浏览
CREATE TABLE IF NOT EXISTS browse(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL, 
	article_id INT UNSIGNED NOT NULL, 
	brower_type VARCHAR(1) DEFAULT '0' COMMENT '浏览器类型,默认无解析',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(article_id) REFERENCES article(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 点赞数
CREATE TABLE IF NOT EXISTS upvote(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL, 
	article_id INT UNSIGNED NOT NULL, 
	type VARCHAR(1) DEFAULT '1' COMMENT '点赞类型，默认为点赞，`0`为踩',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(article_id) REFERENCES article(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 文章评论
CREATE TABLE IF NOT EXISTS comment(
	id INT  PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL COMMENT '发表评论的uid', 
	article_id INT UNSIGNED NOT NULL,
	p_user_id INT UNSIGNED DEFAULT 0 COMMENT '被评论的uid',
	pcomment_id INT DEFAULT 0 COMMENT '0表示无父评论',
	content TEXT NOT NULL,
	upvote INT UNSIGNED DEFAULT 0,
	downvote INT UNSIGNED DEFAULT 0,
	status VARCHAR(1) DEFAULT '1',
	viewed VARCHAR(1) DEFAULT '0' COMMENT 'read为关键字使用viewed,默认没有阅读',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(article_id) REFERENCES article(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 留言板
CREATE TABLE IF NOT EXISTS guestbook(
	id INT PRIMARY KEY AUTO_INCREMENT, 
	user_id INT UNSIGNED NOT NULL, 
	category_id INT UNSIGNED DEFAULT 9999 COMMENT '留言所在版块,默认9999无版块', 
	pcomment_id INT DEFAULT -1 COMMENT '-1表示无父评论', 
	content TEXT NOT NULL,
	upvote INT UNSIGNED DEFAULT 0,
	downvote INT UNSIGNED DEFAULT 0,
	status VARCHAR(1) DEFAULT '1',
	viewed VARCHAR(1) DEFAULT '0' COMMENT '默认没有阅读',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(pcomment_id) REFERENCES guestbook(id),
	FOREIGN KEY(category_id) REFERENCES category(id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 文件
CREATE TABLE IF NOT EXISTS upfiles(
	id INT PRIMARY KEY AUTO_INCREMENT, 
	filetype VARCHAR(1) DEFAULT '0', -- 0 图片, 1 系统资源, 2用户文件
	filename VARCHAR(255)  NOT NULL,
	filepath VARCHAR(255)  NOT NULL,
	filesize VARCHAR(20) NOT NULL,
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;